### ISSUE TITLE
All searches error

### ISSUE THREAD

**Issue by ChrisChinchilla** [ttscoff/searchlink#13]
@ttscoff Fantastic service, and it was working great for me for a short while; I set up a keyboard shortcut, stream deck key… And then suddenly no matter what I do I receive an

"The action “Run Shell Script” encountered an error: “”" error

Any ideas why? Some underlying ruby issue?

**Comment by ttscoff** [comment]
Sorry I missed this when you posted, something is going on with my email notifications.

So there's nothing in the error? Just empty quotes?

**Comment by ttscoff** [comment]
If you open the SearchLink.workflow in Automator, and add a "Get Specified Text" action at the beginning containing a search term, does running it offer any more descriptive error?

Might be worth re-downloading and reinstalling the Service, but you might be onto something with the Ruby issue possibility. It would be nice to get an error out of it, though. Do you have any special ruby install on your machine?

**Comment by ChrisChinchilla** [comment]
@ttscoff Thanks for the continued help. I have installed and re-installed a few times (with home-brew), no change. I can see the script uses the system ruby, and all seems to be well there.

Can i ask what you mean by "containing a search term"? I did a quick debug using Automator without that and I can now see the following if it helps at all? And you can also see my poor attempts at figuring out what you might have meant ;)

<img width="1112" alt="Image" src="https://github.com/user-attachments/assets/0f50b76f-ffba-40dd-83de-79e34a5e4949" />

**Comment by ttscoff** [comment]
Yes, I just meant any text you would normally select and run SearchLink on, where you put "input". It doesn't matter what it is, we just want to see if we can get an actual error message out. In the results pane it looks like it's still just a blank error...

Is there any chance you've modified or deleted your config file? It should be at `~/.config/searchlink/config.yaml`. Check that file and make sure it's valid YAML (or possibly delete/move it and let SearchLink create a new one).

**Comment by ChrisChinchilla** [comment]
@ttscoff Hmm, it gets more interesting… If I remove the config file, then searchLink (I guess), does indeed output a new config file… but not to `~/.config/searchlink/config.yaml`, but instead to the current cursor position… This is a different issue of course 😅

**Comment by ttscoff** [comment]
Are you certain you're using the latest version of SearchLink? There's no reason the current version should be saving anything to ~/.[anything].

**Comment by ChrisChinchilla** [comment]
@ttscoff Yup… Then I tried recreating the config from [here](https://github.com/ttscoff/searchlink/wiki/Configuration) or the output mentioned above and back to the same error again.

<img width="1732" alt="Image" src="https://github.com/user-attachments/assets/4e7d7900-3509-4aee-890c-c080fa673a40" />

Should I try an older version?

**Comment by ttscoff** [comment]
Are you saying it was working at some point? I've tested extensively on my local machine, and I fixed the issue where the new config was being output at the cursor. Are you seeing anything different in the error message?

**Comment by ChrisChinchilla** [comment]
@ttscoff Followed all the steps you suggested in this issue, such as uninstalling, deleting config, etc, and the new version still gets the same initial error…

"The action “Run Shell Script” encountered an error: “”" error

Any other ideas I can dig into to debug?

**Comment by ttscoff** [comment]
Just checking in, are you still experiencing the error? Is the config file being created correctly now?

**Comment by ChrisChinchilla** [comment]
@ttscoff Still exactly the same error, but the config is created correctly.

I do use Homebrew and see this (https://github.com/ttscoff/searchlink/issues/14#issuecomment-2846919747), so i tried a manual download… Still the same.

Hmm, is anything else getting in the way? Keyboard settings, language settings, etc?

Annoyingly, I could have debugged live with you at MacStock, but I'm not coming now due to… erm, "border issues"

**Comment by ChrisChinchilla** [comment]
@ttscoff Pretty familiar, go ahead :)

**Comment by ttscoff** [comment]
Ok, so go ahead and clone this repo. You should then be able to run the 
compile.rb script in the root folder and create a `searchlink.rb` file. 
Make that executable and then run:

     echo "Test search"|./searchlink.rb

See if that gives you any better information than we're getting from the 
Service.

**Comment by ChrisChinchilla** [comment]
@ttscoff 

> Error in "browser_tabs.json": Script plugin script "browser_tabs.js" not found

Huh, as I can find no reference to this in your code, I imagine something else is interfering here…

I have a few shortcuts and services added, but not much added to Automator. Any ideas? Or at least this gives me something to dig more into.

**Comment by ttscoff** [comment]
Is that the full output? That doesn't make any sense, there's no reason SearchLink should be looking for a browser at all. And that's definitely not a Ruby error, which is what I was expecting. Can you show me the full output, including the command you ran?

**Comment by ChrisChinchilla** [comment]
@ttscoff That is the whole output, screenshots attached. I am running latest Homebrew installed Ruby

<img width="1642" alt="Image" src="https://github.com/user-attachments/assets/7bec871d-49d0-4538-84ea-8345e7f0bb4d" />

**Comment by ttscoff** [comment]
I just realized what's happening. The browser_tabs.json is a script 
plugin example I wrote that's part of the demo repo for plugins. Have 
you cloned that at all? If not, I must have some remnant of it in the 
main repo, will grep for that.

-Brett

**Comment by ttscoff** [comment]
No, there's no reference to it in the code, you must have it installed 
at ~/.config/searchlink/plugins. If there's a `browser_tabs.json` file 
there, delete it and see if the issue goes away.

-Brett

**Comment by ChrisChinchilla** [comment]
@ttscoff So… I didn't have that installed, and I didn't have any plugins installed, but cloning the plugins repo to the config directory fixed the problem… Maybe there's some misplaced configuration in the default configuration somewhere? But this has solved my problem, at least!

Thanks, Chris 👏
